const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Behaviors.jumpthru,
		C3.Plugins.Audio,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Platform,
		C3.Behaviors.Fade,
		C3.Behaviors.Physics,
		C3.Plugins.LocalStorage,
		C3.Plugins.GD_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Solid: 0},
	{Bullet: 0},
	{Block: 0},
	{Pin: 0},
	{Rotate: 0},
	{Player: 0},
	{Touch: 0},
	{Keyboard: 0},
	{TiledBackground2: 0},
	{CloudsBackground: 0},
	{Sine: 0},
	{ring: 0},
	{Particles: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Particles2: 0},
	{Sprite6: 0},
	{Sprite9: 0},
	{Particles3: 0},
	{Sprite10: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Jumpthru: 0},
	{Sprite: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite8: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sine2: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Particles4: 0},
	{Sprite30: 0},
	{Sprite41: 0},
	{Audio: 0},
	{LiteTween: 0},
	{Sprite38: 0},
	{Sprite42: 0},
	{Sprite60s: 0},
	{Anchor: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Browser: 0},
	{CoinsFont: 0},
	{ScoreFont: 0},
	{ScoreFontGameOver: 0},
	{Highscorefont: 0},
	{Sprite48: 0},
	{GameoverCoinsfont: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{upgrade1: 0},
	{upgrade2: 0},
	{upgrade3: 0},
	{upgrade4: 0},
	{upgrade5: 0},
	{upgrade6: 0},
	{upgrade7: 0},
	{upgrade8: 0},
	{Selector: 0},
	{skins: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{worldFont: 0},
	{Sprite70: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Sprite73: 0},
	{Sprite74: 0},
	{Sprite75: 0},
	{TiledBackground5: 0},
	{Sprite76: 0},
	{Sprite77: 0},
	{Sprite78: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{Sprite79: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{Sprite82: 0},
	{Sprite83: 0},
	{Sprite84: 0},
	{Sprite85: 0},
	{Sprite86: 0},
	{Sprite87: 0},
	{Sprite88: 0},
	{Selector2: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{Sprite91: 0},
	{Sprite92: 0},
	{RotateScreen: 0},
	{Sprite93: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{Sprite99: 0},
	{Sprite100: 0},
	{Sprite101: 0},
	{Sprite102: 0},
	{TiledBackground8: 0},
	{TiledBackground9: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{Sprite103: 0},
	{Platform: 0},
	{Player2: 0},
	{Sprite104: 0},
	{Particles5: 0},
	{Particles6: 0},
	{Particles7: 0},
	{Sprite105: 0},
	{Sprite106: 0},
	{Sprite107: 0},
	{Sprite108: 0},
	{Sprite109: 0},
	{Sprite110: 0},
	{Fade: 0},
	{Sprite111: 0},
	{Sprite112: 0},
	{number: 0},
	{Sprite113: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Particles8: 0},
	{MenuLightFlare: 0},
	{Sprite116: 0},
	{Sprite117: 0},
	{Sprite118: 0},
	{Sprite120: 0},
	{Physics: 0},
	{Sprite121: 0},
	{Sprite122: 0},
	{Sprite123: 0},
	{rush: 0},
	{player233: 0},
	{player234: 0},
	{Sprite124: 0},
	{Sprite125: 0},
	{Sprite126: 0},
	{Sprite127: 0},
	{Sprite128: 0},
	{Sprite129: 0},
	{Sprite130: 0},
	{wily: 0},
	{rocket5: 0},
	{Sprite131: 0},
	{coheter: 0},
	{Sprite132: 0},
	{Sprite133: 0},
	{TiledBackground12: 0},
	{Sprite134: 0},
	{Sprite135: 0},
	{Sprite136: 0},
	{Sprite137: 0},
	{ring2: 0},
	{Sprite138: 0},
	{Sprite139: 0},
	{realplayer: 0},
	{Particles9: 0},
	{Fade2: 0},
	{GH1: 0},
	{GH2: 0},
	{GH3: 0},
	{Sprite140: 0},
	{Sprite141: 0},
	{Sprite142: 0},
	{GH4: 0},
	{Sprite143: 0},
	{TiledBackground13: 0},
	{TiledBackground14: 0},
	{TiledBackground15: 0},
	{TiledBackground16: 0},
	{GH5: 0},
	{Sprite2: 0},
	{n1: 0},
	{n2: 0},
	{n3: 0},
	{TiledBackground17: 0},
	{Sprite144: 0},
	{Sprite145: 0},
	{Sprite146: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Sprite7: 0},
	{estrellite: 0},
	{Sprite149: 0},
	{Sprite150: 0},
	{Sprite151: 0},
	{Sprite152: 0},
	{TiledBackground18: 0},
	{Sprite153: 0},
	{Sprite154: 0},
	{Sprite155: 0},
	{Sprite156: 0},
	{Sprite157: 0},
	{Sprite158: 0},
	{Sprite159: 0},
	{Sprite160: 0},
	{Sprite96: 0},
	{Sprite161: 0},
	{Sprite162: 0},
	{Sprite163: 0},
	{Sprite164: 0},
	{Sprite165: 0},
	{Sprite166: 0},
	{Sprite167: 0},
	{Sprite168: 0},
	{Sprite169: 0},
	{Sprite170: 0},
	{LocalStorage: 0},
	{Sprite171: 0},
	{Sprite172: 0},
	{rewards: 0},
	{GameDistributionSDK: 0},
	{Sprite9kiz: 0},
	{loading: 0},
	{Sprite20kiz: 0},
	{kiztiled: 0},
	{Sprite43: 0},
	{Sprite119: 0},
	{Sprite173: 0},
	{Sprite174: 0},
	{Family1: 0},
	{sonido: 0},
	{previusworld: 0},
	{Gamemove: 0},
	{world: 0},
	{skin: 0},
	{Coins: 0},
	{Highscore: 0},
	{Score: 0},
	{doubleJump: 0},
	{GameOver: 0},
	{StarShield: 0},
	{stomp: 0},
	{Magnet: 0},
	{Big: 0},
	{Jetpack: 0},
	{RandomLevel: 0},
	{Intro: 0},
	{GameStart: 0},
	{GameSpeed: 0},
	{GravityControl: 0},
	{achi16: 0},
	{achi15: 0},
	{achi14: 0},
	{achi13: 0},
	{achi12: 0},
	{achi11: 0},
	{achi10: 0},
	{achi9: 0},
	{achi8: 0},
	{achi7: 0},
	{achi6: 0},
	{achi5: 0},
	{achi4: 0},
	{achi3: 0},
	{achi2: 0},
	{achi1: 0},
	{IsScreenRotate: 0},
	{toucher: 0},
	{levelselector: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Block: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	CloudsBackground: class extends self.ITiledBackgroundInstance {},
	ring: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite60s: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	CoinsFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFontGameOver: class extends self.ISpriteFontInstance {},
	Highscorefont: class extends self.ISpriteFontInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	GameoverCoinsfont: class extends self.ISpriteFontInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	upgrade1: class extends self.ISpriteInstance {},
	upgrade2: class extends self.ISpriteInstance {},
	upgrade3: class extends self.ISpriteInstance {},
	upgrade4: class extends self.ISpriteInstance {},
	upgrade5: class extends self.ISpriteInstance {},
	upgrade6: class extends self.ISpriteInstance {},
	upgrade7: class extends self.ISpriteInstance {},
	upgrade8: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	skins: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	worldFont: class extends self.ISpriteFontInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Selector2: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Particles7: class extends self.IParticlesInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite109: class extends self.ISpriteInstance {},
	Sprite110: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Sprite112: class extends self.ISpriteInstance {},
	Sprite113: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Particles8: class extends self.IParticlesInstance {},
	MenuLightFlare: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	rush: class extends self.ISpriteInstance {},
	player233: class extends self.ISpriteInstance {},
	player234: class extends self.ISpriteInstance {},
	Sprite124: class extends self.ISpriteInstance {},
	Sprite125: class extends self.ISpriteInstance {},
	Sprite126: class extends self.ISpriteInstance {},
	Sprite127: class extends self.ISpriteInstance {},
	Sprite128: class extends self.ISpriteInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	wily: class extends self.ISpriteInstance {},
	rocket5: class extends self.ISpriteInstance {},
	Sprite131: class extends self.ISpriteInstance {},
	coheter: class extends self.ISpriteInstance {},
	Sprite132: class extends self.ISpriteInstance {},
	Sprite133: class extends self.ISpriteInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite135: class extends self.ISpriteInstance {},
	Sprite136: class extends self.ISpriteInstance {},
	Sprite137: class extends self.ISpriteInstance {},
	ring2: class extends self.ISpriteInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	realplayer: class extends self.ISpriteInstance {},
	Particles9: class extends self.IParticlesInstance {},
	GH1: class extends self.ISpriteInstance {},
	GH2: class extends self.ISpriteInstance {},
	GH3: class extends self.ISpriteInstance {},
	Sprite140: class extends self.ISpriteInstance {},
	Sprite141: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	GH4: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	GH5: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	n1: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	estrellite: class extends self.IParticlesInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	TiledBackground18: class extends self.ITiledBackgroundInstance {},
	Sprite153: class extends self.ISpriteInstance {},
	Sprite154: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Sprite157: class extends self.ISpriteInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	Sprite159: class extends self.ISpriteInstance {},
	Sprite160: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	Sprite168: class extends self.ISpriteInstance {},
	Sprite169: class extends self.ISpriteInstance {},
	Sprite170: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite171: class extends self.ISpriteInstance {},
	Sprite172: class extends self.ISpriteInstance {},
	rewards: class extends self.ISpriteInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	Sprite9kiz: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	Sprite20kiz: class extends self.ISpriteInstance {},
	kiztiled: class extends self.ITiledBackgroundInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite173: class extends self.ISpriteInstance {},
	Sprite174: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}